name: Auto Update on Content Change

on:
  push:
    branches: [ main ]
    paths: [ 'public/content.json' ]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Update docs folder
        run: |
          rm -rf docs
          cp -r dist docs
          
      - name: Commit docs changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git commit -m "Auto-rebuild: Update docs after content change" || exit 0
          git push origin main
          
      - name: Success
        run: |
          echo "✅ Auto-update completed successfully!"
          echo "🌐 Site will be updated in 5-10 minutes"
