name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Deploy message'
        required: false
        default: 'Manual deployment'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Update docs folder
        run: |
          rm -rf docs
          cp -r dist docs
          
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "Manual deploy: ${{ github.event.inputs.message }}"
          git push
          
      - name: Success
        run: |
          echo "✅ Manual deployment completed!"
          echo "🌐 Site will be updated in 5-10 minutes"
